# Generated by Django 4.0.4 on 2022-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0003_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
