# Generated by Django 4.0.4 on 2022-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0007_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, default='defaults.png', null=True, upload_to='messimage/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.ImageField(blank=True, default='defaults.png', null=True, upload_to='imagenote/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
