# Generated by Django 4.0.4 on 2022-08-27 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0008_alter_message_images_alter_note_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('images', models.ImageField(blank=True, max_length=40, null=True, upload_to='eventimage/')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
