# Generated by Django 4.0.4 on 2022-08-30 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0011_alter_event_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(related_name='place', to=settings.AUTH_USER_MODEL),
        ),
    ]
