# Generated by Django 4.0.4 on 2022-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0012_alter_event_options_event_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('user_agent', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('pages', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
