# Generated by Django 4.0.4 on 2022-12-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moonch3api', '0014_userdetail_user_alter_userdetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='pages',
        ),
    ]
